### ISSUE TITLE
MCPI doesn't launch

### ISSUE THREAD

**Issue by EnergitCZ** [MCPI-Devs/MCPIL#10]
Hi,

i installed this project, using: 
`curl -s https://packagecloud.io/install/repositories/Alvarito050506/mcpi-devs/script.deb.sh | sudo bash`
and then `sudo apt-get install mcpil`

The launcher starts but i can't start any version.
It gives me this output in the console:
 ```
/opt/minecraft-pi/minecraft-pi: error while loading shared libraries: libGLESv2.so: cannot open shared object file: No such file or directory
[INFO]: Feature: Touch GUI: Disabled
[INFO]: Setting Game Mode: Survival
[INFO]: Code Block Allocated At: 0x00200000
[ERR]: (/home/pi/proyectos/minecraft-pi-docker/mods/src/extra.c:195) Unable To Find Callsites For 0x00016ec4
```
Energit.

**Comment by Alvarito050506** [comment]
Hello and thanks for the report!

I have to say that, sadly, MCPIL is currently broken for some people, but I'm trying to fix it (without success yet!). I would suggest you using MCPIL [v0.6.2](https://github.com/MCPI-Devs/MCPIL/releases/tag/v0.6.2) to avoid these bugs. This old versions lacks one feature: MCPI-Docker integration. To install it, do:
```sh
sudo apt-get install mcpil=0.6.2
```

Cheers!

**Comment by EnergitCZ** [comment]
Hi again,

thanks for the response.
the older version works!

(btw. good project)

Energit.
