### ISSUE TITLE
[Question] Why did you choose the GPL v2?

### ISSUE THREAD

**Issue by unbeatable-101** [MCPI-Devs/MCPIL#14]
I have seen many projects using it instead of v3, I am just wondering why.

**Comment by Alvarito050506** [comment]
Hello! To be honest, there is no real reason. I just wanted people to use MCPIL under the terms of the GPL v2 or v3, not only the v3, since I used the GPL v2 for some of my projects.

**Comment by unbeatable-101** [comment]
Then shouldn't you have changed the license to say GPL v2 or later? As I understand it, GPL v2 is not compatible to GPL v3. https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility

**Comment by Alvarito050506** [comment]
Actually... ~~Yes, it should.~~ Thanks for noticing it! For some reason, I thought lincensing a work under the GPL v2 would make it compatible with later versions. New versions of MCPIL will be released under the "GPL v2.0 or any later version".

**Comment by StealthHydra179** [comment]
_Issue Should Now Be Closed @Alvarito050506 _
