### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by zachdwilliams** [MCPI-Devs/MCPIL#17]
Hey, there. I found a small spelling mistake in the launcher. In some places where it’s supposed to say “Minecraft” it says “Miecraft”.

**Comment by Alvarito050506** [comment]
_Oh_. Thanks for reporting it! I will fix it soon. Anyways, please use [MCPIL-R](https://github.com/MCPI-Devs/MCPIL-R) or [MCPI-Docker](https://gitea.thebrokenrail.com/thebrokenrail/minecraft-pi-docker), since this project is currently dead/in an hiatus/being killed.
