### ISSUE TITLE
Minecraft Pi Edition does not open in 0.6.1

### ISSUE THREAD

**Issue by NikZapp** [MCPI-Devs/MCPIL#6]
While Minecraft Pocket Edition can be opened using the 0.6.1 launcher, Minecraft Pi can only be opened the normal way (either console or the system menu)

**Comment by nobody5050** [comment]
Hi year that’s an error with the newest version of mcpil. If you downgrade to an older release it should be fixed.

**Comment by NikZapp** [comment]
New info:
While running MCPIL using the console, and trying to launch Minecraft Pi Edition, a Segmentation fault occurs

**Comment by NikZapp** [comment]
Latest version is 0.6.2

**Comment by NikZapp** [comment]
After a downgrade to 0.6.0, an error shows up while running mcpil:
`pi@raspberrypi:~ $ mcpil`
`Traceback (most recent call last):`
`  File "/usr/bin/mcpil", line 41, in <module>`
`    from mcpim import *`
`  File "/usr/lib/python3/dist-packages/mcpim.py", line 68`
`    mod_files = glob.glob(home} + "/.mcpil/mods/*.mcpi");`
`                              ^`
`SyntaxError: invalid syntax`

**Comment by nobody5050** [comment]
0.4.0 should work fine, as it’s working on my end. 0.5.0 most likely works but untested

**Comment by NikZapp** [comment]
For 0.4.0 and 0.5.0, using `sudo apt-get install mcpil=0.4.0` or `sudo apt-get install mcpil=0.5.0`, the version could not be found
`E: Version '0.4.0' for 'mcpil' was not found`
`E: Version '0.5.0' for 'mcpil' was not found`

**Comment by nobody5050** [comment]
Those versions were not uploaded to package cloud, you can download them from github releases

**Comment by NikZapp** [comment]
```pi@raspberrypi:~/Desktop/MCPIL 040/MCPIL-0.4.0 $ python3 build.py
Traceback (most recent call last):
  File "build.py", line 42, in <module>
    sys.exit(main(sys.argv));
  File "build.py", line 36, in main
    py_compile.compile("./proxy/proxy.py", cfile="./build/mcpip.pyc", optimize=2);
  File "/usr/lib/python3.5/py_compile.py", line 122, in compile
    source_bytes = loader.get_data(file)
  File "<frozen importlib._bootstrap_external>", line 826, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './proxy/proxy.py'
```

**Comment by Alvarito050506** [comment]
Hello!

> While Minecraft Pocket Edition can be opened using the 0.6.1 launcher, Minecraft Pi can only be opened the normal way (either console or the system menu)
> [...]
> New info:
While running MCPIL using the console, and trying to launch Minecraft Pi Edition, a Segmentation fault occurs
Also this is version 0.6.1, it is not the latest
> ```shell
> FileNotFoundError: [Errno 2] No such file or directory: './proxy/proxy.py'
> ```

@NikZapp Most of these bugs are likely to be known. MCPIL by itself is a complete mess, but versions prior to 0.6.0 are completer messes... These used a works-on-my-machine monolithic design and it was really, _really_ bad.

On the other hand, I think you should update your OS, at least to `stable`/`buster`, since `MCPIL >= v0.6.2` is not avaiable for `oldstable`/`stretch` (dependency things, you need `Python >= 3.7` to run it) or previous releases, and `<= 0.6.1` are not really supported. By the way, I saw you said you have Python 3.9, so I could upload `v0.6.2` to Packagecloud, but it would still require `Python >= 3.7`. (<s>@nobody5050</s>).

I have the feeling that I'm missing something about this, so let me know if I am...

**Comment by Alvarito050506** [comment]
Ok so, I added MCPIL v0.6.2 to the `oldstable`/`stretch` repo. You still need an updated Python version (`>= 3.7`), and these are only shipped with updated Debian versions (`stable`/`buster`) and _maybe_ backports.

**Comment by NikZapp** [comment]
I have a 3.9 version, so what's the problem with running V0.6.2 using any of the package managers? I don't know how to update my OS without breaking anything but i will look it up.
Still, 0.6.2 will be easier to install with just `sudo apt-get install mcpil`, so you should upload it
P.S: I was writing this before your comment was sent

**Comment by Alvarito050506** [comment]
Oh, it's ok... I just didn't upload the package because in a "vanill"a Debian Stretch distro it would be broken. Remember to update your package index (`sudo apt-get update`) before installing `mcpil=0.6.2`.

**Comment by NikZapp** [comment]
I mean, Raspbian isn't vanilla Debian, but ok

**Comment by Alvarito050506** [comment]
No no, I mean, any Debian Stretch distro without compiling Python 3.7 or adding backports or Buster repos.

**Comment by NikZapp** [comment]
Oh, now this pops up
```shell
pi@raspberrypi:~ $ mcpil
  File "/usr/bin/mcpil", line 75
    username = f"{username}\x00";
                               ^
SyntaxError: invalid syntax
```
I don't know how the ` f"..." ` operation works, but i'm sure it will be easy to fix by myself (at least i hope so)

**Comment by NikZapp** [comment]
Oh wait, forgot to use python 3.9
```shell
pi@raspberrypi:~ $ python3.9 /usr/bin/mcpil
Traceback (most recent call last):
  File "/usr/bin/mcpil", line 39, in <module>
    from mcpicentral import *
ModuleNotFoundError: No module named 'mcpicentral'
```

**Comment by Alvarito050506** [comment]
Yeah, I was about to send this comment xD

> It's probably because you're trying to run it with Python 3.5, try `python3.9 /usr/bin/mcpil`, change the hashbang from `#!/usr/bin/env python3` to `#!PYTHON3.9_LOCATION`, or try some obscure `update-alternatives` trick (actually the last one is the "cannonical" way xD).

**Comment by Alvarito050506** [comment]
> Oh wait, forgot to use python 3.9
> 
> ```shell
> pi@raspberrypi:~ $ python3.9 /usr/bin/mcpil
> Traceback (most recent call last):
>   File "/usr/bin/mcpil", line 39, in <module>
>     from mcpicentral import *
> ModuleNotFoundError: No module named 'mcpicentral'
> ```
Hmm... Is Python 3.9 looking for modules in the generic Python 3 modules dir?

**Comment by NikZapp** [comment]
I have found your repos with the needed libraries, i will check if just copying them will work

**Comment by Alvarito050506** [comment]
Oh, ok... It's still weird that it does not work with Python 3.9, since it _should_. Anyways later I'll try to compile it and test MCPIL.

**Comment by NikZapp** [comment]
You have the libraries installed, meanwhile i'm still installing them
If anyone from the future needs to know where those libraries are, there are the links:
[libmcpi](https://github.com/MCPI-Devs/libmcpi)
[mcpi-central](https://github.com/MCPI-Devs/mcpi-central)
[modpi](https://github.com/MCPI-Devs/modpi)
[proxy](https://github.com/MCPI-Devs/proxy)

**Comment by NikZapp** [comment]
Also you should probably edit the Build section for libmcpi
Old:
```shell
make
make test-local # For testing before install
make install
make test-global # For testing after install
```
New:
```shell
# -j 4 argument means that all 4 raspberry pi cores will work on the task. That will speed up the process 4 times, but will use all of the processor resources
make -j 4
make -j 4 test-local # For testing before install
make -j 4 install
make -j 4 test-global # For testing after install
```

**Comment by NikZapp** [comment]
It may be helpful too

**Comment by Alvarito050506** [comment]
Probably yeah, I'm not sure if it'll make a big difference since it's a small project, but who knows? :shrug:

P.S.: I know this isn't your first issue, I just added the label to "pin" it.

**Comment by NikZapp** [comment]
By the way, i sent you a discord message since you seem to be offline

**Comment by Alvarito050506** [comment]
Ok, I'll close this due to inactivity.
