### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by mobilegmYT** [MCPI-Devs/MCPIL#7]
Hello, I just downloaded this. When I try to launch a version or profile with the launcher, a window quickly opens, then closes. After that, nothing happens.

**Comment by nobody5050** [comment]
Which version are you using?

**Comment by mobilegmYT** [comment]
I tried all 4 default versions but none worked. I launched it from the terminal, and here's the output when I choose a version:
`[INFO]: Feature: Touch GUI: Disabled
[INFO]: Setting Game Mode: Survival
[INFO]: Feature: Survival Mode: Disabled
[INFO]: Feature: Fix Bow & Arrow: Disabled
[INFO]: Feature: Fix Attacking: Disabled
[INFO]: Feature: Mob Spawning: Disabled
[INFO]: Feature: Fancy Graphics: Disabled
[INFO]: Setting Username: StevePi
[INFO]: Feature: Disable Autojump By Default: Disabled
[INFO]: Feature: Show Block Outlines: Disabled
[INFO]: Feature: Fix Sign Placement: Disabled
[INFO]: Feature: Expand Creative Inventory: Disabled
[INFO]: Feature: Touch GUI: Disabled
[INFO]: Setting Game Mode: Survival
[INFO]: Feature: Survival Mode: Disabled
* failed to add service - already in use?`

**Comment by nobody5050** [comment]
Which version of Debian are you using?

**Comment by mobilegmYT** [comment]
I'm using the latest version of raspbian(buster)

**Comment by nobody5050** [comment]
Would you mind restarting your pi and trying again?

**Comment by mobilegmYT** [comment]
I restarted, but it still says the same thing.

**Comment by Alvarito050506** [comment]
Hello!

I'm pretty sure it is an OpenGL/EGL/MESA/VirGL problem. What is your memory split? And which RPi version/model are you using?

**Comment by mobilegmYT** [comment]
I'm currently using a RPI 4 8gb ram with a memory split of 256

**Comment by Alvarito050506** [comment]
Hmm... I have a RPi 4 with 4 GiB RAM, and the only way I got rid of that error was setting the GPU memory to 128 MiB and the GL driver to `GL (Fake KMS)`.

**Comment by mobilegmYT** [comment]
Hm. I set the openGL driver to fake kms and also set gpu_mem to 128mb, but it's still going me the error.

**Comment by Alvarito050506** [comment]
Sorry for the (maybe dumb) question but, did you reboot?

**Comment by mobilegmYT** [comment]
Yes

**Comment by Alvarito050506** [comment]
Hmm... No idea, maybe you could ask in the RPi forums? Because the last [thread](https://www.raspberrypi.org/forums/viewtopic.php?t=12581) on the topic is _very, very, very_ old.

**Comment by mobilegmYT** [comment]
Hmm ok. mcpil does have https://github.com/xobs/mcrpi-wrapper right?

**Comment by Alvarito050506** [comment]
Sort of, it currently uses the `mcpi-docker` [`libcompat`](https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-docker/src/branch/master/mods/src/compat.c).

**Comment by Alvarito050506** [comment]
@mobilegmYT Try by using using `GL Legacy`, I tried and MCPI runs with that config in my RPi 4.

**Comment by mobilegmYT** [comment]
How do I switch to that?

**Comment by Alvarito050506** [comment]
Via `raspi-config`:
```sh
# Launch it
sudo raspi-config
```
Go to `Advanced Options->GL Driver`, and then select `Legacy`, reboot if it asks you to do so.

**Comment by mobilegmYT** [comment]
Ok, so I did that, but I got the error `[ERR]: GLFW Error: X11: RandR gamma ramp support seems brokenminecraft-pi: /build/glfw3-UExs5r/glfw3-3.2.1/src/input.c:153: glfwGetInputMode: Assertion `window != NULL' failed.`From: Álvaro TorralbaSent: November 8, 2020 2:39 PMTo: MCPI-Devs/MCPILCc: RPI News; MentionSubject: Re: [MCPI-Devs/MCPIL] Unable to launch (#7) @mobilegmYT Try by using using GL Legacy, I tried and MCPI runs with that config in my RPi 4.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Alvarito050506** [comment]
That error sounds familiar, let me check the Discord server (by the way, [join us](https://discord.gg/DCwcpyf) if the total lack of privacy does not concern you! :wink:).

**Comment by Alvarito050506** [comment]
Yes, someone already reported it in the Discord server, just opened an issue (#8) to track it. By the way, I'm closing this issue as resolved tomorrow, if it does not get any activity.

**Comment by Alvarito050506** [comment]
Closing...
