### ISSUE TITLE
GLFW Error: Assertion window != NULL failed

### ISSUE THREAD

**Issue by Alvarito050506** [MCPI-Devs/MCPIL#8]
**Complete error messages:**
> [ERR] GLFW Error: X11: RandR gamma ramp seems to be broken
> minecraft-pi: /build/glfw3-UExs5r/glfw3-3.2.1/src/input.c:153: glfwGetInputMode: Assertion \`window != NULL' failed.

**Versions:**
 + MCPIL `v0.7.1`
 + libmcpi-docker `v1.3.0`.

**Notes:**
 + Reported by @NikZapp (in our [Discord server](https://discord.gg/DCwcpyf)) and @mobilegmYT (in #7).
 + The error seems to be related to libmcpi-docker, since it outputs the `[ERR]` prefix.

**Comment by TheBrokenRail** [comment]
This is an error GLFW is emitting. This could occur if you are using a weird X11 server or a weird GL driver.

**Comment by Alvarito050506** [comment]
Ok, closing this as it seems to be related to the underlying protocols and programs.
