### ISSUE TITLE
Doesnt start

### ISSUE THREAD

**Issue by finnie2006** [MCPI-Devs/MCPIL#9]
I installed MCPIL
but when i click launch it doesnt start

**Comment by Alvarito050506** [comment]
Hello @finnie2006! Could you provide some info about how you installed MCPIL, which version you installed, your OS and if you already had MCPI installed?

**Comment by mobilegmYT** [comment]
I’m 70% sure he is having the same problem as me since a lot of my friends who I asked to test it for me on raspbian also had this problem.

**Comment by mobilegmYT** [comment]
Try enabling your Fake KMS drivers in raspi-config, as well as to launch mcpil with the command `LD_LIBRARY_PATH="/usr/lib/arm-linux-gnueabihf:${LD_LIBRARY_PATH}" mcpil`

**Comment by Alvarito050506** [comment]
@mobilegmYT Oh, did that solve your problem? Because MCPIL by itself does the `LD_LIBRARY_PATH="/usr/lib/arm-linux-gnueabihf:${LD_LIBRARY_PATH}"` part...

**Comment by mobilegmYT** [comment]
Yes, it did. I asked one of my friends who helped test for me but didn't do any troubleshooting to run the command, and it worked for him.

**Comment by Alvarito050506** [comment]
Oh, thanks for the feedback! I'll look up into that part of the code, clearly something is failing there...

**Comment by Alvarito050506** [comment]
@finnie2006 Try to update now, I just released a bugfix.

**Comment by finnie2006** [comment]
Oke nice I will try

**Comment by finnie2006** [comment]
Survival

pi@raspberrypi:~ $ mcpil
/opt/minecraft-pi/minecraft-pi: error while loading shared libraries:
libGLESv2.so: cannot open shared object file: No such file or
directory
[INFO]: Feature: Touch GUI: Disabled
[INFO]: Setting Game Mode: Survival
[INFO]: Code Block Allocated At: 0x00200000
[ERR]: (/home/pi/proyectos/minecraft-pi-docker/mods/src/extra.c:195)
Unable To Find Callsites For 0x00016ec4


Creative
pi@raspberrypi:~ $ mcpil
/opt/minecraft-pi/minecraft-pi: error while loading shared libraries:
libGLESv2.so: cannot open shared object file: No such file or
directory
[INFO]: Feature: Touch GUI: Disabled
[INFO]: Setting Game Mode: Survival
[INFO]: Code Block Allocated At: 0x00200000
[ERR]: (/home/pi/proyectos/minecraft-pi-docker/mods/src/extra.c:195)
Unable To Find Callsites For 0x00016ec4

**Comment by Alvarito050506** [comment]
Hello! This one is a really weird error, since MCPI (installed from the official repos) provides `libGLESv2` by itself, and it is one of the dependencies of MCPIL. So, how did you install MCPIL? And, what OS are you using?

**Comment by finnie2006** [comment]
I am using Raspberry Pi OS (32bit)

I did install it like this

sudo apt-get update

sudo apt-get upgrade


curl -s https://packagecloud.io/install/repositories/Alvarito050506/mcpi-devs/script.deb.sh | sudo bash

sudo apt-get install mcpil

**Comment by Alvarito050506** [comment]
Ok, thanks to @finnie2006 in our Discord server: You may need to install `libgles2-mesa` as the following:
```
sudo apt-get install libgles2-mesa
```
Future releases will include it as a dependencie so you will not need to worry.
